# Generated by Django 5.1 on 2024-09-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0002_redactedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactedfile',
            name='original_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='redactedfile',
            name='processed_path',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
